### ISSUE TITLE
BugBusters - Potential FlashLoan attack in _getExchangeRate function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-06-dodo-judging#228]
BugBusters

high

# Potential FlashLoan attack in _getExchangeRate function

## Summary
The _getExchangeRate function  may be vulnerable to flash loan attacks due to its reliance on the totalSupply value obtained from an external contract.

## Vulnerability Detail
Flash loans enable borrowers to manipulate large amounts of funds within a single transaction. In the context of the _getExchangeRate function, if an attacker can manipulate the totalSupply value of the token in question, it can lead to incorrect exchange rate calculations and potentially disrupt the intended functionality of the smart contract.

## Impact
If an attacker successfully manipulates the totalSupply value through a flash loan attack, it can result in inaccurate exchange rate calculations. This can have various consequences, such as incorrect interest calculations, liquidity imbalances, or mispricings, which may adversely impact the stability and reliability of the smart contract.

## Code Snippet
https://github.com/sherlock-audit/2023-06-dodo/blob/main/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L230-L236

## Tool used

Manual Review

**Comment by KuTuGu** [comment]
Escalate
1. This issue is invalid, because totalSupply cannot be manipulated, which is only internally mint / burn:
- https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L41
- https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L57

2. #136 is invalid, because flashloan can't change exchangeRate, which only increases over time. See the sponsor's comments
3. #22 and #60 describe the effect of withdrawReserves on interest rates, which is not a duplicate of this.

**Comment by sherlock-admin2** [comment]
> Escalate
> 1. This issue is invalid, because totalSupply cannot be manipulated, which is only internally mint / burn:
> - https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L41
> - https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L57
> 
> 2. #136 is invalid, because flashloan can't change exchangeRate, which only increases over time. See the sponsor's comments
> 3. #22 and #60 describe the effect of withdrawReserves on interest rates, which is not a duplicate of this.
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Nabeel-javed** [comment]
escalate for 10 usdc

As borrow increase, the exchange rate increases. If a user deposits a significant relative amount of tokens immediately before a large borrow transaction they will be getting dTokens at a lower exchange rate, then if they withdraw those tokens immediately after the borrow transaction (backrunning), they will be effectively trading their dTokens at a higher exchange rate.

so this issue is valid

**Comment by sherlock-admin2** [comment]
> escalate for 10 usdc
> 
> As borrow increase, the exchange rate increases. If a user deposits a significant relative amount of tokens immediately before a large borrow transaction they will be getting dTokens at a lower exchange rate, then if they withdraw those tokens immediately after the borrow transaction (backrunning), they will be effectively trading their dTokens at a higher exchange rate.
> 
> so this issue is valid
> 
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by maarcweiss** [comment]
I think the issue is valid. But agree with the escalation too. So makes me think that this issue: #228 is invalid, and  #136 according to sponsors comments and escalation from Kutugu it is not really profitable. So I have to agree to invalidate #136 too. Keeping #60 and #22 as dups and valid

**Comment by hrishibhat** [comment]
@KuTuGu 
https://github.com/sherlock-audit/2023-06-dodo-judging/issues/228#issuecomment-1650049795
Do you have any comments to add to this?

**Comment by KuTuGu** [comment]
I don't know why the warden said that the exchangeRate will rise, because every time mint amount is depended on the current exchangeRate, that is, the growth multiple of totalCash and totalSupply is the same, which is the current exchangeRate, so it will remain unchanged.
You can check out this line of code: https://github.com/sherlock-audit/2023-06-dodo/blob/a8d30e611acc9762029f8756d6a5b81825faf348/new-dodo-v3/contracts/DODOV3MM/D3Vault/D3VaultFunding.sol#L39
totalCash increases the amount, totalSupply increases the dTokenAmount, and their ratio is still exchangeRate.

**Comment by hrishibhat** [comment]
@Nabeel-javaid 
> As borrow increase, the exchange rate increases. 

Seems like this statement is incorrect. Adn this is a non issue. Do you have anything to add ?

**Comment by hrishibhat** [comment]
@traceurl 
This issue seems to be invalid based on the above comments

**Comment by traceurl** [comment]
@hrishibhat I agree. Should be invalid.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on above comments

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kutugu](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/228/#issuecomment-1649928819): accepted
- [Nabeel-javaid](https://github.com/sherlock-audit/2023-06-dodo-judging/issues/228/#issuecomment-1650049795): rejected

**Comment by IAm0x52** [comment]
No fix needed and linked PR doesn't pertain to this issue
